on:
  push:
    branches:
    - main
    
jobs:
  test:
    name: test the vs code extension
    runs-on: ubuntu-latest
    steps:
      - name: Install packages and test
        run: |
          apt install node
          npm install
          npm run test
